name: 'Upload Release Asset'
description: 'Uploads an asset to the current release.'
inputs:
  file:
    description: 'Path to the file to upload.'
    required: true
  file-type:
    description: 'Content type header, if not application/zip'
    required: false
    default: 'application/zip'
outputs:
  asset-url:
    description: 'URL to the newly created asset.'
    value: ${{ steps.upload-asset.outputs.asset-url }}
  asset-id:
    description: 'ID of the newly created asset.'
    value: ${{ steps.upload-asset.outputs.asset-id }}
runs:
  using: 'composite'
  steps:
    - name: Upload asset
      id: upload-asset
      env:
        FILE: ${{ inputs.file }}
        FILE_TYPE: ${{ inputs.file-type }}
      shell: bash
      run: ${{ github.action_path }}/upload.sh
